{% extends "layout.swig" %}

{% block title %}404-短网址{% endblock %}

{% block content %}
	<div class="container">
        <header>
            <a href="javascript:void(0)">
                <h1>404 Not Found</h1>
            </a>
        </header>
        <section>
            <div class="tab_wrap">你要浏览的页面未找到</div>
        </section>
        <footer>
            <p class="copyright">©2016 shyling</p>
        </footer>
    </div>
{% endblock %}